services:

  db:
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: fusion
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - my-networks
  
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - my-networks

volumes:
  pgdata:
    driver: local
networks:
  my-networks:
    driver: bridge